### PR TITLE
Migrate old docs

### LINKED ISSUE #10: Migrate old docs
Brad asked on Discord, if we would like to help them migrate the gitbook over to the new docs.
> Brad | Battlesnake — 06/25/2022
Random question - if we set up a docusaurus, would folks help us migrate the gitbook content?

so I've converted all the pages on the old docs into a checklist, there might be some which might fit better on the wiki part, like useful algorithms. However for now let's move everything over and worry about this later. 

### General
  - [x] Overview
  - [x] FAQ

### Guides
  - [x] Quick Start Coding Guide
  - [x] Developer Tips 
  - [x] League Guide
  - [x] Challenges Guide 

### References 
  - [x] API Reference 
  - [x] Starter Projects 
  - [x] Customizations 
  - [x] Game Rules 
  - [x] Game Modes
  - [x] Hosting Suggestions 
  - [x] Choosing an Engine Region
  - [x] Useful Algorithms

### Community 
- [x] Contributing 
- [x] Links 
  - Github
  - Discord
  - Twitch
  - Awesome List
  - Feedback

### Policies 
- [x] Mission and Values
- [x] Code of Conduct
- [ ] Diversity
- [ ] Prize Policy
- [x] Privacy Policy
- [x] Terms of Service

### PR DESCRIPTION
**Pull request by DaBultz**
Just opening a PR as a draft, so discussions can occur while it's being worked on, in 1 central location :)

When merged, this closes #10

### CODE REVIEW

**Comment by bvanvugt** [comment]
@DaBultz this is a great first run, thanks for pulling this together! Reading through it in detail, there are some small changes we'd like to make to the content, but nothing that couldn't be addressed after merging this (or is specific to this migration effort).?

Is your plan to merge this sooner, or add ALL migrations prior to merging?

**Comment by DaBultz** [comment]
> @DaBultz this is a great first run, thanks for pulling this together! Reading through it in detail, there are some small changes we'd like to make to the content, but nothing that couldn't be addressed after merging this (or is specific to this migration effort).?
> 
> Is your plan to merge this sooner, or add ALL migrations prior to merging?

@bvanvugt plan is get all the content over and then we can run through and do the updates, feel it's easier to see what changes we wish, when it's in-front of us... still working on the the rest, the API was the most work, rest would be coming in over the next hours. 

I've made a section for all the pages, which did not fit in how I understood the current organization, so they are easy to find + to discuss.

I'm aware of the build fails, I will fix that at the end (easy to fix them via a simple find a replace project wide)

**Comment by DaBultz** [comment]
All pages should be converted over, there's an WIP tab for the ones I did not know where we wanted them. 

There was 1 thing, which could not be converted to docusaurus which is: 
image

the places this was used on gitbook, is commented out with  `TODO` comment above. so they can easily be found. I've opened for review.

**Comment by bvanvugt** [comment]
Looks good, WIP section is a good call. Not having that one section is fine, that's one of the parts we want to change anyway 👍 

I'm happy with this if @coreyja is!

**Review by bvanvugt — APPROVED** [review]

**Review by coreyja — APPROVED** [review]
Looks great to me!

I'm looking at the expected build issue here 🤔 
I think the Github Check name might have changed since I did the branch protection rules, will look into fixing that quick

**Comment by coreyja** [comment]
Github Checks look all better 🎉

**Pull request merged**
