### PR TITLE
Removed the starter template for C++

### PR DESCRIPTION
**Pull request by OneBogdan01**
### That repo does not work with the new API, it does not run at all on Replit
Also, I am confused about the pull request templates and I do not have the option to open an issue.
Edit: Also [this](https://docs.battlesnake.com/community/contributing) link is not working (found in the contributing.md file)

### CODE REVIEW

**Comment by xtagon** [comment]
Hi @OneBogdan01,

Thank you for contributing! My personal opinion is that it would be better for someone to bring the C++ starter template up to date and fix any API incompatibilities/fix the documentation issues rather than to remove it entirely.

I see you already opened an issue on their repo here: https://github.com/DAChenScratch/Starter-Battlesnake-Cpp-with-replit/issues/3

Because the Battlesnake docs repo doesn't allow creating issues, a more appropriate place would be the Battlesnake Discussions here: https://github.com/orgs/BattlesnakeOfficial/discussions

I'd be curious to see what others think. There might be someone else in the community who knows C++ and wants to help get things up to date.

**Comment by OneBogdan01** [comment]
Hello! I completely agree with you. I think that remaking the C++ starter template would be ideal.

**Comment by xtagon** [comment]
I'm not too familiar with the modern C++ ecosystem. What is the recommended HTTP server for C++ these days?

**Comment by OneBogdan01** [comment]
I am currently learning modern C++, but I have absolutely no experiene with http requests.

**Review by bvanvugt — APPROVED** [review]

**Pull request merged**
