### PR TITLE
[fix] Customizations marked as optional

### PR DESCRIPTION
**Pull request by Vam-Jam**
Page in question: https://docs.battlesnake.com/api/objects/battlesnake

Marked customization as optional, as some requests do not contain it.

```
TRACE request{method=POST uri=/end version=HTTP/1.1}: axum::rejection: rejecting request status=422 body="Failed to deserialize the JSON body into the target type: board.snakes[0]: missing field `customization` at line 1 column 999" rejection_type="axum::extract::rejection::JsonDataError"  
```

### CODE REVIEW

**Review by xtagon — APPROVED** [review]

**Comment by bvanvugt** [comment]
@Vam-Jam Hey do you have a game ID for an example of this? Would love to dig into what's causing this.

**Comment by Vam-Jam** [comment]
5ff3e4f6-560c-45ef-857b-2c27e715ed58

**Comment by Vam-Jam** [comment]
I figured out the issue. Forgot an 's' on the end, that's what happens with trying to code and debug late at night. Sorry about that! Looks like it does always send customizations.

**Comment by bvanvugt** [comment]
Ahhh awesome, okay. That saves me some debugging time :) Thanks!

**Pull request closed without merging**
