### PR TITLE
Update CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by ADITYADAS1999**
changing the broken link   https://docs.battlesnake.com/community/contributing   page to the contribution guideline page 
 https://web.archive.org/web/20220526045103/https://docs.battlesnake.com/community/contributing

### CODE REVIEW

**Review by naomi-lgbt — CHANGES_REQUESTED** [review]
I don't believe we want to use the web archive version - but I'm not sure where the actual contributing docs went.

**Comment by bvanvugt** [comment]
Agree with @naomi-lgbt - also not sure how it got lost in the mix. Is there interest in porting the web archive version into the new setup?

Maybe @andrewdmaclean could help

**Comment by andrewdmaclean** [comment]
Hey @ADITYADAS1999 👋  Great to see your PR.

What that link does for you in provide reference to what you would need to recreate here in the new Battlesnake Docs, rather than link to the wayback machine archive.

[Here is some information](https://docusaurus.io/docs) on getting started with Docusaurus which is the framework we use for our document 

[Here is the original code](https://github.com/BattlesnakeOfficial/docs-old/tree/master/community/contributing) referenced in the Wayback Archive that you would need to recreate with your PR in this repo.

If you are able to make the change we can keep the PR open, otherwise we can close and then re-open a new PR in the future.

Let me know!

**Comment by ADITYADAS1999** [comment]
> Hey @ADITYADAS1999 👋 Great to see your PR.
> 
> What that link does for you in provide reference to what you would need to recreate here in the new Battlesnake Docs, rather than link to the wayback machine archive.
> 
> [Here is some information](https://docusaurus.io/docs) on getting started with Docusaurus which is the framework we use for our document
> 
> [Here is the original code](https://github.com/BattlesnakeOfficial/docs-old/tree/master/community/contributing) referenced in the Wayback Archive that you would need to recreate with your PR in this repo.
> 
> If you are able to make the change we can keep the PR open, otherwise we can close and then re-open a new PR in the future.
> 
> Let me know!

Hi, [andrewdmaclean](https://github.com/andrewdmaclean) 
I want to add a simple contributing guideline for beginners, Just in 3/4 steps. So that everyone can easily navigate to contribute by only read the .readme . Can I add and work with this ?

**Comment by DaBultz** [comment]
Hey @ADITYADAS1999, just chiming in to say: maybe if you could quickly say the 3/4 steps you would like to add, so the others can say what they think :) you are however welcome to add the lost contribution page to the docs. 

Pretty sure, this is would be fine with the @andrewdmaclean and the others. 

NOTE: Ignore me closing and reopening the PR, was a complete accident.

**Comment by ADITYADAS1999** [comment]
> Hey @ADITYADAS1999, just chiming in to say: maybe if you could quickly say the 3/4 steps you would like to add, so the others can say what they think :) you are however welcome to add the lost contribution page to the docs.
> 
> Pretty sure, this is would be fine with the @andrewdmaclean and the others.
> 
> NOTE: Ignore me closing and reopening the PR, was a complete accident.

Hey [DaBultz](https://github.com/DaBultz), sorry for little delay. I will add all things by tomorrow.

**Comment by bvanvugt** [comment]
Closing this for now since no consensus was reached.

**Pull request closed without merging**
