### PR TITLE
Add the contributing guide and README

### LINKED ISSUE #1: Write the contributing guide + readme

### PR DESCRIPTION
**Pull request by 770grappenmaker**
Title says it all.

### CODE REVIEW

**Review by jlafayette — APPROVED** [review]
Awesome!  This seems like it covers the basics really well

**Comment by 770grappenmaker** [comment]
Fixed the conflicts :smile:

**Review by coreyja — APPROVED** [review]
💯 

I'm going to merge this in!

**Comment by coreyja** [comment]
Fixes #1

**Pull request merged**
